# This is a basic workflow to help you get started with Actions

name: docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_doc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install Doxygen 1.9.2
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9
          wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
          tar -xvzf doxygen-1.9.2.linux.bin.tar.gz
          ln -s doxygen-1.9.2/bin/doxygen doxygen
      - name: Generate Documentation
        run: ./doxygen Doxyfile
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
