name: Builds

on:
  push:
      

jobs:
  build:
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        clang_version: [14]
    steps:
    - uses: actions/checkout@v3
          
    - run: clang++-${{ matrix.clang_version }} --version

    - run: cmake --version

    - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
    - run: sudo apt-get update
    - run: sudo apt-get install llvm-${{ matrix.clang_version }}
    - run: sudo apt-get install llvm-${{ matrix.clang_version }}-dev
    - run: sudo apt-get install llvm-${{ matrix.clang_version }}-runtime
    - run: sudo apt-get install libclang-cpp${{ matrix.clang_version }}
    - run: sudo apt-get install libclang-cpp${{ matrix.clang_version }}-dev
    - run: ls -lh /usr/lib/llvm-14/lib
    - run: ls -lh /usr/lib/llvm-14/lib/cmake
    - run: ls -lh /usr/lib/llvm-14/bin
    - run: ls -lh /usr/share
    - run: ls -lh /usr/share/llvm-14
    - run: ls -lh /usr/share/llvm-14/cmake
    - run: ls -lh /usr/share/llvm-14/bin
      
    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.10.0

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: clang++-${{ matrix.clang_version }}
      run: cmake $GITHUB_WORKSPACE -DLLVM_ROOT=/usr/lib/llvm-${{ matrix.clang_version }}/cmake

    - name: Build Instantiator
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -- -j2

    - name: Install Instantiator
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: sudo cmake --build . --target install --config $BUILD_TYPE -- -j2
      
    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: bats -r .
